version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}
    volumes:
      - ./data/static_collected:/app/data/static_collected
      - ./data/media:/app/data/media
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data:z

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./data/static_collected:/static
    depends_on:
      - web